### ISSUE TITLE
[Error] SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by KoJaeMin** [SearchMyCoding/QuestionServer#17]
아래와 같이 에러 발생
<img width="1082" alt="스크린샷 2024-04-15 오후 8 45 15" src="https://github.com/SearchMyCoding/QuestionServer/assets/77095298/31c5c58d-c6ec-4d33-bf1c-c549f5c0db0f">

```zsh
import { Entity, Column, OneToMany } from "typeorm";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at tryToRequire (/Users/gojaemin/Desktop/project/SMC/QuestionServer/src/util/ImportUtils.ts:21:17)
    at importOrRequireFile (/Users/gojaemin/Desktop/project/SMC/QuestionServer/src/util/ImportUtils.ts:35:25)
```

**Comment by KoJaeMin** [comment]
최근 nestjs는 build시 webpack option으로 하나의 파일로 build되기에 에러가 발생하지 않을 수 있습니다. 하지만 이전 버전들은 그러지 않기에 빌드 후 Entity 파일들을 참조해야 됩니다.
